"root":
  setup_env_script: "none" #'/home/HPC/sterbini/2021_12_07/miniconda/bin/activate'
  generations:
    1: # Make the particle distribution
      job_folder: "master_jobs/000_make_part_distribution"
      job_executable: 000_make_distrib.py # has to be a python file
      files_to_clone: # relative to the template folder
        - clean_it.sh
      run_on: "local_pc"
    2: # Launch the pymask and prepare the xlines
      job_folder: "master_jobs/001_machine_model"
      job_executable: 000_pymask.py # has to be a python file
      files_to_clone: # relative to the template folder
        - optics_specific_tools.py
        - clean_it.sh
      run_on: "slurm"
      htc_job_flavor: "microcentury" # optional parameter to define job flavor, default is espresso
    3: # Launch the tracking
      job_folder: "master_jobs/002_tracking_job"
      job_executable: 000_track.py # has to be a python file
      files_to_clone: # relative to the template folder
        - clean_it.sh
      run_on: "slurm"
      htc_job_flavor: "tomorrow" #"tomorrow" # optional parameter to define job flavor, default is espress
